name: Build Check

on:
  push:
    branches:
      - "main"
  workflow_call:
    inputs:
      ksu_variant:
        required: true
        type: string
        default: "Next"
      ksu_commit:
        required: false
        type: string
        default: ""

jobs:
  build-check-matrix:
    name: Check - ${{ matrix.android_version }} ${{ matrix.kernel_version }} (${{ matrix.sub_level }})
    strategy:
      fail-fast: false
      matrix:
        include:
          # A12 5.10
          - android_version: "android12"
            kernel_version: "5.10"
            sub_level: "43"
            os_patch_level: "2021-08"
          - android_version: "android12"
            kernel_version: "5.10"
            sub_level: "X"
            os_patch_level: "lts"

          # A13 5.10
          - android_version: "android13"
            kernel_version: "5.10"
            sub_level: "107"
            os_patch_level: "2022-04"
          - android_version: "android13"
            kernel_version: "5.10"
            sub_level: "X"
            os_patch_level: "lts"

          # A13 5.15
          - android_version: "android13"
            kernel_version: "5.15"
            sub_level: "41"
            os_patch_level: "2022-06"
          - android_version: "android13"
            kernel_version: "5.15"
            sub_level: "X"
            os_patch_level: "lts"

          # A14 5.15
          - android_version: "android14"
            kernel_version: "5.15"
            sub_level: "110"
            os_patch_level: "2023-06"
          - android_version: "android14"
            kernel_version: "5.15"
            sub_level: "X"
            os_patch_level: "lts"

          # A14 6.1
          - android_version: "android14"
            kernel_version: "6.1"
            sub_level: "25"
            os_patch_level: "2023-06"
          - android_version: "android14"
            kernel_version: "6.1"
            sub_level: "X"
            os_patch_level: "lts"

          # A15 6.6
          - android_version: "android15"
            kernel_version: "6.6"
            sub_level: "30"
            os_patch_level: "2024-07"
          - android_version: "android15"
            kernel_version: "6.6"
            sub_level: "X"
            os_patch_level: "lts"

          # A16 6.12
          - android_version: "android16"
            kernel_version: "6.12"
            sub_level: "23"
            os_patch_level: "2025-05-exp"
          - android_version: "android16"
            kernel_version: "6.12"
            sub_level: "X"
            os_patch_level: "lts"

    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: ${{ matrix.android_version }}
      kernel_version: ${{ matrix.kernel_version }}
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      ksu_variant: ${{ inputs.ksu_variant || 'Next' }}
      ksu_commit: ${{ inputs.ksu_commit || '' }}
