name: Kernel Config - A12 5.10

permissions:
  contents: write # Allow writing to repository contents
  actions: write # Allows triggering actions

on:
  workflow_call:
    inputs:
      ksu_variant:
        required: true
        type: string
      ksu_commit:
        required: false
        type: string
      build_bypass:
        required: true
        type: boolean

jobs:
  build-kernels-a12:
    name: "5.10.${{ matrix.sub_level }}-${{ matrix.os_patch_level }}"
    strategy:
      fail-fast: false
      matrix:
        include:
        # Deprecated series (Android 12 - 5.10)
        
          
        - sub_level: "198"
          os_patch_level: "2023-11"
        
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      android_version: "android12"
      kernel_version: "5.10"
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      ksu_variant: ${{ inputs.ksu_variant }}
      ksu_commit: ${{ inputs.ksu_commit }}
      build_bypass: ${{ inputs.build_bypass }}
